framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: general-failed

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            general-failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed

            async_user_repo_update:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: user_repo_update
                failure_transport: failed_user_repo_update

            failed_user_repo_update:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed_user_repo_update
            # sync: 'sync://'

        routing:
             'App\Message\Github\UpdateUserRepoMessage': async_user_repo_update

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
